### ISSUE TITLE
does anyone get  Cannot read property 'replace' of undefined, when running serve-specs?

### ISSUE THREAD

**Issue by andresmijares** [johnpapa/ng-patterns-testing#7]
I'm having this error Uncaught TypeError: Cannot read property 'replace' of undefined mocha.js 5937 when running the serve-specs for some reason, I cannot find a way to solve.

Also when running autotest ERROR [launcher]: No binary for PhantomJS browser on your platform.
  Please, set "PHANTOMJS_BIN" env variable.

Any guessing?

**Comment by jaredmustard** [comment]
I have the same issue. Any resolutions to this year old thread?

- Update, that was the solution. I updated to the latest mocha package via npm and got the error to quite down. Thanks anyway!
